config/routes.rb
ProjectBOA::Application.routes.draw do
  mount S3Multipart::Engine => "/s3_multipart"
  root to: 'users#new'
  get '/sessions/destroy' => 'sessions#destroy', as: 'logout'
  resources :users, except: :index
  resources :sessions, only: :create
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :positions, only: :index
  resources :grips, only: :show
  resources :instructional_videos
end

app/models/grip.rb
class Grip < ActiveRecord::Base
  belongs_to :sub_position
  has_many :instructional_videos
  has_many :major_categories, through: :instructional_videos
end

app/models/instructional_video.rb
class InstructionalVideo < ActiveRecord::Base
  belongs_to :grip
  belongs_to :major_category
  belongs_to :instructional_video_uploader
end

app/models/major_category.rb
class MajorCategory < ActiveRecord::Base
  has_many :instructional_videos
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :sub_positions
  has_many :grips, through: :sub_positions

  validates_presence_of :name
end

app/models/sub_position.rb
class SubPosition < ActiveRecord::Base
  belongs_to :position
  has_many :grips

  validates_presence_of :name
  validates_presence_of :position_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible \
    :username,
    :email,
    :password,
    :password_confirmation,
    :first_name,
    :last_name,
    :rank,
    :gym,
    :about

  has_secure_password
  validates_presence_of :password, on: :create
  validates_presence_of :username, on: :create
  validates_presence_of :email,    on: :create

  def send_password_reset
    generate_token(:password_reset_token)
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :eject

  private

  def user_params
    params.require(:user).permit(:user, :username, :email, :password, :password_confirmation)
  end

  def eject
    redirect_to root_path if session[:id].nil?
  end
end

app/controllers/grips_controller.rb
class GripsController < ApplicationController

  def show
    @grip = Grip.includes(:instructional_videos, :major_categories).find(params[:id])
  end
end

app/controllers/instructional_videos_controller.rb
class InstructionalVideosController < ApplicationController

  def index
    @instructional = InstructionalVideo.new
  end

  def new
    redirect_to positions_path
  end

  def create
    @video = InstructionalVideo.new(video_params)
    if @video.save
      flash[:notice] = 'Video uploaded.'
      redirect_to positions_path
    else
      flash[:notice] = 'Upload failed.'
      render :new
    end
  end

  private

  def video_params
    params.require(:instructional_video).permit(:title)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :eject

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    user.send_password_reset if user
    redirect_to root_url, flash: { notice: 'Email sent with password reset instructions.' }
  end

  def edit
    @user = User.find_by!(password_reset_token: params[:id])
  end

  def update
    @user = User.find_by!(password_reset_token: params[:id])
    if @user.update_attributes(user_params)
      redirect_to root_url, flash: { notice: 'Password reset.' }
    else
      render :edit, flash: { notice: 'Error: password not reset.' }
    end
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
    @top = Position.includes(:sub_positions, :grips).where(top: true)
    @bottom = Position.includes(:sub_positions, :grips).where(top: false)
    @neutral = Position.includes(:sub_positions, :grips).where(top: nil)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :eject

  def create
    user = User.find_by_email(params[:email])
    login(user, params[:password])
  end

  def destroy
    session.clear
    redirect_to root_url, notice: 'Logged out!'
  end

  private

  def login(user, password)
    if authenticated?(user, password)
      set_session(user.id)
    else
      bounce
    end
  end

  def authenticated?(user, password)
    user && user.authenticate(password)
  end

  def set_session(id)
    session[:id] = id
    redirect_to positions_path, notice: 'Logged in.'
  end

  def bounce
    redirect_to root_url, notice: 'Invalid email or password.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :eject

  def new
    redirect_to positions_path if session[:id]
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to positions_path, notice: 'Signed up!'
    else
      flash[:notice] = 'Fields cannot be blank.'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    user = User.find(session[:id])
    user.update_attributes(params[:user])
    redirect_to user, notice: 'Profile updated.'
  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end
end

app/views/grips/show.html.erb
<h2><%= @grip.sub_position.position.name %> > <%= @grip.sub_position.name %> > <%= @grip.name %></h2>
<br>
<ul>
  <% @grip.instructional_videos.each do |vid| %>
    <ul>
      <li>Title: <%= vid.title %></li>
      <li>Url: <%= vid.url %></li>
      <li>Description: <%= vid.description %>
      <li>Category: <%= vid.major_category.name %>
      <li>Video:
        <video width="400" height="300" controls>
          <source src="https://s2e7pa89pb6x71.cloudfront.net/boaproject/Far+Leg+Calf+Slicer+from+X-Guard.mov" type="video/mp4">
          Your browser does not support the video tag.
        </video>
      </li>
    </ul>
  <% end %>
</ul>

app/views/instructional_videos/index.html.erb
<%= multipart_uploader_form(input_name: 'uploader',
                            uploader: 'InstructionalVideoUploader',
                            button_class: 'submit-button',
                            button_text: 'Upload selected videos',
                            html: %Q{<button class="upload-button">Select videos</button>},
                            types: %w(wmv avi mp4 mkv mov mpeg)) %>

app/views/instructional_videos/new.html.erb
<h1>Information for your uploaded video</h1>
<%= form_for @instructional do |f| %>
  <% if @instructional.errors.any? %>
    <h2><%= pluralize(@instructional.errors.count, '  error') %> prohibited this video from being saved.  </h2>
    <ul>
      <% @instructional.errors.full_messages.each do |  msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :key %>
  <p>File: <%= @instructional.instructional_name %></p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :major_category, 'Category' %>
  <%= f.select :major_category, options_for_select(['Sweep', 'Submission', 'Guard Pass', 'Reversal']) %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_user %>
      <nav>
        <ul>
          <li>
            <%= link_to 'Profile', current_user %>
          </li>
          <li>
            <%= link_to 'Home', positions_path %>
          </li>
          <li>
            <%= link_to 'Upload', instructional_videos_path %>
            </li>
          <li>
            <%= link_to 'Log out', logout_path %>
          </li>
        </ul>
      </nav>
    <% end %>
    <%= yield %>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.full_messages.any? %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit "Update Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <p>
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </p>
  <%= submit_tag "Reset Password" %>
<% end %>

app/views/positions/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1>Positions</h1>

<h2>Neutral</h2>
<ul>
  <% @neutral.each do |position| %>
    <li><%= position.name %></li>
      <ul>
        <% position.sub_positions.each do |sub_position| %>
          <li><%= sub_position.name %></li>
            <ul>
              <% sub_position.grips.each do |grip| %>
                <li><%= link_to grip.name, grip %></li>
              <% end %>
            </ul>
        <% end %>
      </ul>
  <% end %>
</ul>

<h2>Top</h2>
<ul>
  <% @top.each do |position| %>
    <li><%= position.name %></li>
      <ul>
        <% position.sub_positions.each do |sub_position| %>
          <li><%= sub_position.name %></li>
          <ul>
              <% sub_position.grips.each do |grip| %>
                <li><%= link_to grip.name, grip %></li>
              <% end %>
            </ul>
        <% end %>
      </ul>
  <% end %>
</ul>

<h2>Bottom</h2>
<ul>
  <% @bottom.each do |position| %>
    <li><%= position.name %></li>
      <ul>
        <% position.sub_positions.each do |sub_position| %>
          <li><%= sub_position.name %></li>
          <ul>
              <% sub_position.grips.each do |grip| %>
                <li><%= link_to grip.name, grip %></li>
              <% end %>
            </ul>
        <% end %>
      </ul>
  <% end %>
</ul>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>

  <% if current_user.errors.any? %>
    <% current_user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    <% end %>

  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :rank %>
    <%= f.text_field :rank %>
  </p>
  <p>
    <%= f.label :gym %>
    <%= f.text_field :gym %>
  </p>
  <p>
    <%= f.label :about %>
    <%= f.text_field :about %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<span style='font-size:72px'>hip<b>scape</b></span>
<br>
<p><i>Perfect your game.</i></p>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% if !current_user %>
  <h3> Log in </h3>
  <%= form_tag(sessions_path) do %>
    <p>
      <%= label_tag("Email") %>
      <%= text_field_tag("email") %>
    </p>
    <p>
      <%= label_tag("Password") %>
      <%= password_field_tag("password") %>
    </p>
    <p><%= link_to "Forgot your password?", new_password_reset_path %></p>
    <%= submit_tag("Log In") %>
  <% end %>

  <h3>Sign Up</h3>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    <% end %>
    <p>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>
    <%= f.submit %>
  <% end %>
<% end %>

<% if current_user %>
  <%= link_to 'Sign Out', logout_path %>
<% end %>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1>Profile</h1>
<ul>
  <li>
    <p>Username: </p>
    <p><%= @user.username %></p>
  </li>
  <li>
    <p>First Name: </p>
    <p><%= @user.first_name %></p>
  </li>
  <li>
    <p>Last Name: </p>
    <p><%= @user.last_name %></p>
  </li>
  <li>
    <p>Rank: </p>
    <p><%= @user.rank %></p>
  </li>
  <li>
    <p>Gym: </p>
    <p><%= @user.gym %></p>
  </li>
  <li>
    <p>About: </p>
    <p><%= @user.about %></p>
  </li>
</ul>

<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(current_user) %>
<% end %>